name = 'durable-post-error'
main = "src/index.ts"
compatibility_date = "2024-08-16"

[[durable_objects.bindings]]
name = "thing"
class_name = "Thing"
 
 
 [[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Thing"]